//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocSign.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class e_Mess
    {
        public int ID { get; set; }
        public string Receiver { get; set; }
        public string Sender { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string CreateBy { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string Note { get; set; }
        public string Status { get; set; }
        public Nullable<int> DocID { get; set; }
        public string BodyContent { get; set; }
    
        public virtual Document Document { get; set; }
    }
}
